global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "litestar"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8080"]
  
  - job_name: "passenger"
    metrics_path: /passenger_metrics
    static_configs:
      - targets: ["localhost:8080"]
    scrape_interval: 15s
